config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :categories

      resources :grocery_stores

      resources :ingredients

      resources :meals

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "meals#index"
  resources :categories
  resources :grocery_stores
  resources :ingredients
  resources :meals
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  # Direct associations

  belongs_to :category

  belongs_to :store,
             class_name: "GroceryStore"

  belongs_to :meal,
             optional: true,
             counter_cache: true

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    meal.to_s
  end
end

app/controllers/api/v1/ingredients_controller.rb
class Api::V1::IngredientsController < Api::V1::GraphitiController
  def index
    ingredients = IngredientResource.all(params)
    respond_with(ingredients)
  end

  def show
    ingredient = IngredientResource.find(params)
    respond_with(ingredient)
  end

  def create
    ingredient = IngredientResource.build(params)

    if ingredient.save
      render jsonapi: ingredient, status: :created
    else
      render jsonapi_errors: ingredient
    end
  end

  def update
    ingredient = IngredientResource.find(params)

    if ingredient.update_attributes
      render jsonapi: ingredient
    else
      render jsonapi_errors: ingredient
    end
  end

  def destroy
    ingredient = IngredientResource.find(params)

    if ingredient.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: ingredient
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[show edit update destroy]

  def index
    @q = Ingredient.ransack(params[:q])
    @ingredients = @q.result(distinct: true).includes(:meal, :store,
                                                      :category).page(params[:page]).per(10)
  end

  def show; end

  def new
    @ingredient = Ingredient.new
  end

  def edit; end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      message = "Ingredient was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @ingredient, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient, notice: "Ingredient was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @ingredient.destroy
    message = "Ingredient was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to ingredients_url, notice: message
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:meal_id, :name, :category_id,
                                       :store_id, :cost, :photo)
  end
end

app/views/ingredients/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Ingredient #<%= ingredient.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Meal</dt>
      <dd>
        <% if @ingredient.meal.present? %>
          <%= link_to ingredient.meal, ingredient.meal %>
        <% end %>
      </dd>

      <dt>Name</dt>
      <dd><%= ingredient.name %></dd>

      <dt>Category</dt>
      <dd>
        <% if @ingredient.category.present? %>
          <%= link_to ingredient.category, ingredient.category %>
        <% end %>
      </dd>

      <dt>Store</dt>
      <dd>
        <% if @ingredient.store.present? %>
          <%= link_to ingredient.store, ingredient.store %>
        <% end %>
      </dd>

      <dt>Cost</dt>
      <dd><%= ingredient.cost %></dd>

      <dt>Photo</dt>
      <dd>
        <%= cl_image_tag @ingredient.photo, class: "img-fluid" %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back ingredient, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_ingredient_url(ingredient), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to ingredient, method: :delete, data: { confirm: "Do you really want to delete this ingredient?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(ingredient.updated_at) %> ago
  </div>
</div>

app/views/ingredients/_form.html.erb
<% was_validated = ingredient.errors.any? %>

<%= form_with(model: ingredient, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% meal_class = "form-control" %>
    <% meal_was_invalid = ingredient.errors.include?(:meal) %>

    <% if was_validated %>
      <% if meal_was_invalid %>
        <% meal_class << " is-invalid" %>
      <% else %>
        <% meal_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :meal_id %>
    <%= f.collection_select :meal_id, Meal.all, :id, :to_s, {}, class: "form-control" %>
    <% if meal_was_invalid %>
      <% ingredient.errors.full_messages_for(:meal).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = ingredient.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% ingredient.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = ingredient.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :to_s, {}, class: "form-control" %>
    <% if category_was_invalid %>
      <% ingredient.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% store_class = "form-control" %>
    <% store_was_invalid = ingredient.errors.include?(:store) %>

    <% if was_validated %>
      <% if store_was_invalid %>
        <% store_class << " is-invalid" %>
      <% else %>
        <% store_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :store_id %>
    <%= f.collection_select :store_id, GroceryStore.all, :id, :to_s, {}, class: "form-control" %>
    <% if store_was_invalid %>
      <% ingredient.errors.full_messages_for(:store).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% cost_class = "form-control" %>
    <% cost_was_invalid = ingredient.errors.include?(:cost) %>

    <% if was_validated %>
      <% if cost_was_invalid %>
        <% cost_class << " is-invalid" %>
      <% else %>
        <% cost_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :cost %>
    <%= f.text_field :cost, class: cost_class, placeholder: "Enter cost" %>
    <% if cost_was_invalid %>
      <% ingredient.errors.full_messages_for(:cost).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% photo_class = "form-control" %>
    <% photo_was_invalid = ingredient.errors.include?(:photo) %>

    <% if was_validated %>
      <% if photo_was_invalid %>
        <% photo_class << " is-invalid" %>
      <% else %>
        <% photo_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
    <% if photo_was_invalid %>
      <% ingredient.errors.full_messages_for(:photo).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/ingredients/_ingredients_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "ingredients_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :cost, "Cost" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :cost_gteq, :class => "form-control", :placeholder => "Cost greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :cost_lteq, :class => "form-control", :placeholder => "Cost less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :store_store_name_cont, "Store store_name contains" %>
    <%= f.text_field :store_store_name_cont, :class => "form-control", :placeholder => "Store store_name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :category_category_name_cont, "Category category_name contains" %>
    <%= f.text_field :category_category_name_cont, :class => "form-control", :placeholder => "Category category_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/ingredients" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#ingredients_filters">
  Show filters
</a>

app/views/ingredients/_list_item.html.erb
<%= link_to ingredient, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= ingredient %>
    <small class="text-muted">
      <%= time_ago_in_words(ingredient.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/ingredients/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Ingredient #<%= @ingredient.id %>
      </h2>

      <div class="card-body">
        <%= render "form", ingredient: @ingredient %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Ingredients

      <%= link_to new_ingredient_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "ingredients/ingredients_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Ingredients

        <%= link_to new_ingredient_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @ingredients, partial: "list_item", as: :ingredient %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @ingredients, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Ingredient
      </h2>

      <div class="card-body">
        <%= render "form", ingredient: @ingredient %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @ingredient, partial: "card", as: :ingredient %>
  </div>
</div>